services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - flask-network
    restart: unless-stopped

  
  flask-app:
    image: nomisatti/flask-mongo-devops:latest
    #build:
      #context: ./app/
      #dockerfile: Dockerfile
    container_name: flask-app-cont
    ports:
      - 5000:5000
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - flask-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - flask-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana_password
    networks:
      - flask-network
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs' 
    networks:
      - flask-network
    restart: unless-stopped

  cadvisor:
    image:  gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports: 
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - flask-network
    restart: unless-stopped
networks:
  flask-network:

volumes:
  mongo-data:

